services:
  node:
    container_name: pro3-node
    restart: unless-stopped
    image: pro3/node
    build:
      context: .
      dockerfile: ./services/node/Dockerfile
    ports:
      - 80:80
    volumes:
      - ../app:/home/node/app
    env_file:
      - ./services/node/files/.env