services:
  node:
    container_name: pro3-node
    restart: unless-stopped
    image: pro3/node
    build:
      context: .
      dockerfile: ./services/node/Dockerfile
    # networks:
    #   - hello_proxy
    ports:
      - 80:80
      # - 443:433
      # - 8080:8080
    volumes:
      - ../app:/home/node/app
    env_file:
      - ./services/node/files/.env

# networks:
#   hello_proxy